serviceAccount: "projects/ai-chatbot-training/serviceAccounts/ai-chatbot-training@appspot.gserviceaccount.com"
logsBucket: "gs://ai-chatbot-training.appspot.com"
options:
  logging: GCS_ONLY
  machineType: "E2_MEDIUM"

steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://ai-chatbot-training.appspot.com/models/animagineXLV3_v30.safetensors",
        "./animagineXLV3_v30.safetensors",
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://ai-chatbot-training.appspot.com/models/sdxl_vae.safetensors",
        "./sdxl_vae.safetensors",
      ]
  - name: "ubuntu"
    args: ["ls", "-l"]

  # Step to log in to Docker Hub
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo $(gcloud secrets versions access latest --secret=docker-hub-token) > /workspace/docker-hub-token

  # Step to log in to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cat /workspace/docker-hub-token | docker login -u tsuneakihmt --password-stdin

  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--dockerfile=Dockerfile"
      - "--context=dir://."
      - "--destination=gcr.io/ai-chatbot-training/anisd-a1111-runpod:latest"
      - "--cache=true"
      - "--cache-ttl=24h"
      - "--cache-repo=gcr.io/ai-chatbot-training/kaniko-cache"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ai-chatbot-training/anisd-a1111-runpod:latest"]

timeout: "3600s"

