serviceAccount: "projects/ai-chatbot-training/serviceAccounts/ai-chatbot-training@appspot.gserviceaccount.com"
logsBucket: "gs://ai-chatbot-training.appspot.com"
options:
  logging: GCS_ONLY

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo $(gcloud secrets versions access latest --secret=docker-hub-token) | docker login -u tsuneakihmt --password-stdin

  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--dockerfile=Dockerfile"
      - "--context=dir://."
      - "--destination=gcr.io/ai-chatbot-training/anisd-a1111-runpod:latest"
      - "--cache=true"
      - "--cache-ttl=24h"
      - "--cache-repo=gcr.io/ai-chatbot-training/kaniko-cache"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ai-chatbot-training/anisd-a1111-runpod:latest"]

